name: lint
on: push
jobs:
  format:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          toolchain: stable
      - run: cargo fmt -- --check
